### ISSUE TITLE
RLP encoding is not deterministic.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-rlp#6]
This simple source code provides different length all the time
```
import rlp, nimcrypto/sysrand

var p1: array[65, byte]
var p2: array[64, byte]
var p3: array[32, byte]
discard randomBytes(p1)
discard randomBytes(p2)
discard randomBytes(p3)

var p0 = rlp.encode((p1, p2, p3))
echo len(p0)
```

Every run of compiled binary provides different length.

**Comment by cheatfate** [comment]
After latest fix `byte` problem got resolved, but it still has problems for everything not a `BLOB`.

**Comment by yglukhov** [comment]
If it's not a blob/string, the rlp length is less deterministic. So that's not an issue probably.

**Comment by cheatfate** [comment]
@yglukhov, according to official RLP tests you are wrong.
https://github.com/ethereum/tests/wiki/RLP-Tests

**Comment by zah** [comment]
Yes, the overall length on an RLP list will depend on the length of the individual items. If the items are numbers for example, each number will be stored with the minimal number of bytes required for it, so a list of random numbers is indeed likely to have a different length on each randomization.

**Comment by cheatfate** [comment]
This example is also produces different length, for 1 byte values:
```nim
import rlp, nimcrypto/sysrand

var p1: array[65, byte]
discard randomBytes(p1)

var p0 = rlp.encode((p1[0], p1[1], p1[2]))
echo len(p0)
```

**Comment by yglukhov** [comment]
@cheatfate, this is expected. Any single scalar is encoded with a length that depends on its value, not its size.
